In [ ]:
import numpy as np
import pandas as pd
marks=np.array([75,85,95,88])
print("Marks:",marks)
print("Type:",type(marks))
print("Number of dimension:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)

Marks: [75 85 95 88]
Type: <class 'numpy.ndarray'>
Number of dimension: 1
Shape: (4,)
Number of elements: 4

In [ ]:
print("Original:",marks)
print("Add 5:",marks+5)

Original: [75 85 95 88]
Add 5: [ 80  90 100  93]

In [ ]:
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())

Sum: 343
Mean: 85.75
Maximum: 95

In [ ]:
print("First marks:",marks[0])
print("Second marks:",marks[2])
print("Last marks:",marks[-1])

First marks: 75
Second marks: 95
Last marks: 88

In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[2:])

Index 1 to 3: [85 95 88]
First three: [75 85 95]
From index 2: [95 88]

In [ ]:
student_marks=np.array([
    [78,65,78],
    [56,89,90],
    [54,7,89]
])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 65 78]
 [56 89 90]
 [54  7 89]]
Shape: (3, 3)

In [ ]:
print("First student:",student_marks[0])
print("Second student:",student_marks[1])
print("Third student:",student_marks[2])

First student: [78 65 78]
Second student: [56 89 90]
Third student: [54  7 89]

In [ ]:
data={
    "Name":["Anu","Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,89]
}
df=pd.DataFrame(data)
df

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     89

In [ ]:
print("Shape:",df.shape)
print("Column:",df.columns)

Shape: (4, 3)
Column: Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.tail()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     89

In [ ]:
df.describe()

           Marks
count   4.000000
mean   85.250000
std     6.652067
min    76.000000
25%    82.750000
50%    87.000000
75%    89.500000
max    91.000000

In [ ]:
print("First row:")
print(df.iloc[0])
print("Second row:\n",df.iloc[1])
print("First three row:\n",df.iloc[:3])
print("Last two row:\n",df.iloc[-2:])
print("First two row and first two columns:\n",df.iloc[:2,:2])

First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object
Second row:
 Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object
First three row:
     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
Last two row:
     Name Branch  Marks
2  Kiran    CSE     76
3  Priya   AIML     89
First two row and first two columns:
     Name Branch
0    Anu    CSE
1  Rahul   AIML

In [ ]:
print("First three rows:\n",df.iloc[:3])
print("Rows 1 to 3,Name and Marks:",df.iloc[1:4,0:3])

First three rows:
     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
Rows 1 to 3,Name and Marks:     Name Branch  Marks
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     89

In [ ]:
high_marks=df[df["Marks"]>90]
print(high_marks)

    Name Branch  Marks
1  Rahul   AIML     91

In [ ]:
print("Students from CSE:",df[df["Branch"]=="CSE"])
print("Students scoring 85 or above:",df[df["Marks"]>=85])

Students from CSE:     Name Branch  Marks
0    Anu    CSE     85
2  Kiran    CSE     76
Students scoring 85 or above:     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     89

In [ ]:
data={
    "Name":["Asha","Bharat","Chetan","Divya","Easha"],
    "Department":["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,95,68],
    "Attendance":[82,94,88,96,75]
}
students=pd.DataFrame(data)
print(students)

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96
4   Easha        ISE     68          75

In [ ]:
print("name:",students["Name"])
print("Marks:",students["Marks"])

name: 0      Asha
1    Bharat
2    Chetan
3     Divya
4     Easha
Name: Name, dtype: object
Marks: 0    72
1    91
2    84
3    95
4    68
Name: Marks, dtype: int64

In [ ]:
print("Students scored more than 80:",students[students["Marks"]>=80])

Students scored more than 80:      Name Department  Marks  Attendance
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96

In [ ]:
print("Students whose attendance is above 85:",students[students["Attendance"]>=85])

Students whose attendance is above 85:      Name Department  Marks  Attendance
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96

In [ ]:
students.iloc[0:3]

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88

In [ ]:
students['Marks'].mean()

np.float64(82.0)

In [ ]:
students['Marks'].max()

95

In [ ]:
students[students["Department"]=="CSE"]

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
2  Chetan        CSE     84          88

In [ ]:
students[(students["Marks"]>=90)&(students["Attendance"]>85)]

     Name Department  Marks  Attendance
1  Bharat        ISE     91          94
3   Divya       AIML     95          96